# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: end-of-file-fixer
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v2.0.2'
  hooks:
  - id: autopep8
- repo: https://github.com/gitleaks/gitleaks.git
  rev: 'v8.17.0'
  hooks:
  - id: gitleaks
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
    exclude: .*jenkins-slave$
